# Generated by Django 5.2.3 on 2025-06-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('did', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdid',
            name='user',
        ),
        migrations.AddField(
            model_name='userdid',
            name='public_key',
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdid',
            name='did',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
